on:
  push:
    tags:
      - '*'

name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install (python)
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install (poetry)
        run: python -m pip install poetry
      - name: Install (invoke)
        run: python -m pip install invoke
      - name: Build
        run: invoke build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
